% Edit the graph of the function to insert an x-label, y-label, title, mark the zero and
% the value of the integral. Then generate the M-file which corresponds to the new
% figure and include it here: 


function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 01-Mar-2016 10:26:23

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1);

box(axes1,'on');